//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework4Example.Data
{
    using System;
    
    public partial class AddntlContactInfo
    {
        public string Active { get; set; }
        public string CellPhone { get; set; }
        public string EmailAddress { get; set; }
    }
}
