//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework4Example.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRS_EMP_EMPLOYEE
    {
        public string EMPLOYEE_ID { get; set; }
        public string STREAM_ID { get; set; }
        public string GRADE_CODE_ID { get; set; }
        public int DEVELOPMENT_STAGE_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public Nullable<int> WRES_ID { get; set; }
        public Nullable<int> APP_ID { get; set; }
        public string RES_NAME { get; set; }
        public string EMPLOYEMENT_STATUS_CODE { get; set; }
        public string EMPLOYEE_ALIAS { get; set; }
        public string EMPLOYEE_SID { get; set; }
        public bool ACTIVE { get; set; }
        public string PICTURE { get; set; }
        public Nullable<System.DateTime> HIRING_DATE { get; set; }
        public string DIVISION { get; set; }
        public string SUBDIVISION { get; set; }
        public Nullable<System.DateTime> NEXT_REVIEW_PERIOD { get; set; }
        public string COMMENT { get; set; }
        public string CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE_TIME { get; set; }
        public string LAST_MOD_USER { get; set; }
        public System.DateTime LAST_MOD_DATE_TIME { get; set; }
        public int VERS { get; set; }
    }
}
