// <auto-generated />
namespace OdeToFood.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Add_reviewer_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_reviewer_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201412272316017_Add_reviewer_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
